version: '2'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
    ports: 
      - 3300:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080
      
  web:
      build: ./
      volumes:
        - ./web:/home/project
      ports:
          - 3000:3000
      command: nodemon app.js
