version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: node-architecture
    volumes:
      - "./database:/data/db"
    ports:
      - 27010:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: root
      ME_CONFIG_MONGODB_AUTH_DATABASE: node-architecture
  web:
      build: ./
      volumes:
        - ./web:/home/project
      ports:
          - 3000:3000
      command: nodemon app.js
